#Assignment Task Overview
Project Title: Smart Mobility & Ride Analytics
Analyze a real-world ride-hailing business dataset using concepts from Mathematics for Data Science, Probability, Statistics, and Hypothesis Testing.
Your goal is to uncover operational insights, validate assumptions, and support decision-making using analytical methods.

##●Prepare and clean the dataset using NumPy and Pandas

In [16]:
import pandas as pd
import numpy as np
from scipy import stats
import warnings

warnings.filterwarnings("ignore")

# Dataset URL
url = "https://github.com/GeethaGunasekaran1/Dataset_rep/raw/refs/heads/main/Trip_Analysis.xlsx"

# Read Excel File
df = pd.read_excel(url)

print("\nDataset Loaded Successfully")

print("\nFirst 5 Rows")
print(df.head())

print("\nDataset Shape")
print(df.shape)

print("\nColumn Names")
print(df.columns.tolist())

print("\nDataset Information")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

duplicate_count = df.duplicated().sum()

print(f"\nDuplicate Rows Found: {duplicate_count}")

df = df.drop_duplicates().copy()

print("Duplicate Rows Removed Successfully")

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:

    median_value = df[col].median()

    df[col] = df[col].fillna(median_value)

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:

    if not df[col].mode().empty:

        mode_value = df[col].mode()[0]

        df[col] = df[col].fillna(mode_value)

print("\nMissing Values Handled Successfully")

for col in df.columns:

    if 'date' in col.lower() or 'time' in col.lower():

        if df[col].dtype == 'object':
            df[col] = pd.to_datetime(
                df[col],
                format='mixed',
                errors='coerce',
                dayfirst=True
            )

            print(f"{col} converted to datetime")

for col in numeric_cols:

    Q1 = df[col].quantile(0.25)

    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - (1.5 * IQR)

    upper_bound = Q3 + (1.5 * IQR)

    df = df[
        (df[col] >= lower_bound) &
        (df[col] <= upper_bound)
    ]

print("\nOutliers Removed Successfully")

pickup_cols = [
    col for col in df.columns
    if 'pickup' in col.lower()
]

drop_cols = [
    col for col in df.columns
    if 'drop' in col.lower()
]

if pickup_cols and drop_cols:

    pickup_col = pickup_cols[0]

    drop_col = drop_cols[0]

    if (
        pd.api.types.is_datetime64_any_dtype(df[pickup_col]) and
        pd.api.types.is_datetime64_any_dtype(df[drop_col])
    ):

        df['Trip_Duration_Minutes'] = (
            (df[drop_col] - df[pickup_col]).dt.total_seconds() / 60
        )

        print("\nTrip Duration Feature Created")

print("\nRemaining Missing Values")
print(df.isnull().sum())

print("\nStatistical Summary")
print(df.describe())

print("\nData Cleaning Completed Successfully")


Dataset Loaded Successfully

First 5 Rows
   Trip_Distance  Fare_Amount Ride_Category  Surge_Multiplier  \
0              8   270.569350        Shared               2.5   
1             21   275.161032       Economy               2.5   
2             16   359.748971       Economy               2.0   
3             12   264.044264       Premium               1.5   
4              9   225.256916        Shared               2.0   

   Customer_Rating Ride_Time  
0                3  Non-Peak  
1                3  Non-Peak  
2                5  Non-Peak  
3                5  Non-Peak  
4                2  Non-Peak  

Dataset Shape
(200, 6)

Column Names
['Trip_Distance', 'Fare_Amount', 'Ride_Category', 'Surge_Multiplier', 'Customer_Rating', 'Ride_Time']

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Trip_Distance   

##Apply Linear Algebra concepts (vectors, matrices, determinant, eigenvalues/eigenvectors)

In [17]:
selected_cols = numeric_cols[:4]

matrix_data = df[selected_cols]

A = matrix_data.to_numpy()

print("\nSelected Columns for Matrix:")
print(selected_cols.tolist())

print("\nMatrix Shape:")
print(A.shape)

vector1 = A[0]
vector2 = A[1]

print("\nVector 1:")
print(vector1)

print("\nVector 2:")
print(vector2)

vector_add = vector1 + vector2

print("\nVector Addition:")
print(vector_add)

dot_product = np.dot(vector1, vector2)

print("\nDot Product:")
print(dot_product)

magnitude_v1 = np.linalg.norm(vector1)

print("\nMagnitude of Vector 1:")
print(magnitude_v1)

square_matrix = matrix_data.corr().to_numpy()

print("\nSquare Matrix:")
print(square_matrix)

transpose_matrix = square_matrix.T

print("\nTranspose Matrix:")
print(transpose_matrix)

matrix_multiplication = np.dot(square_matrix, transpose_matrix)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

determinant = np.linalg.det(square_matrix)

print("\nDeterminant of Matrix:")
print(determinant)

eigenvalues, eigenvectors = np.linalg.eig(square_matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

matrix_rank = np.linalg.matrix_rank(square_matrix)

print("\nMatrix Rank:")
print(matrix_rank)

if determinant != 0:

    inverse_matrix = np.linalg.inv(square_matrix)

    print("\nInverse Matrix:")
    print(inverse_matrix)

else:

    print("\nMatrix is Singular. Inverse Cannot Be Computed.")

eigen_df = pd.DataFrame({
    "Eigenvalues": eigenvalues
})

eigen_df.to_excel(
    "Linear_Algebra_Results.xlsx",
    index=False
)

print("\nResults Saved Successfully")

print("\nLinear Algebra Analysis Completed Successfully")


Selected Columns for Matrix:
['Trip_Distance', 'Fare_Amount', 'Surge_Multiplier', 'Customer_Rating']

Matrix Shape:
(199, 4)

Vector 1:
[  8.        270.5693496   2.5         3.       ]

Vector 2:
[ 21.         275.16103167   2.5          3.        ]

Vector Addition:
[ 29.         545.73038127   5.           6.        ]

Dot Product:
74633.39137519975

Magnitude of Vector 1:
270.71576043038834

Square Matrix:
[[ 1.00000000e+00  1.08718148e-02  1.45027981e-02 -8.19387453e-02]
 [ 1.08718148e-02  1.00000000e+00 -2.27511044e-04  7.51261017e-02]
 [ 1.45027981e-02 -2.27511044e-04  1.00000000e+00 -3.26631810e-02]
 [-8.19387453e-02  7.51261017e-02 -3.26631810e-02  1.00000000e+00]]

Transpose Matrix:
[[ 1.00000000e+00  1.08718148e-02  1.45027981e-02 -8.19387453e-02]
 [ 1.08718148e-02  1.00000000e+00 -2.27511044e-04  7.51261017e-02]
 [ 1.45027981e-02 -2.27511044e-04  1.00000000e+00 -3.26631810e-02]
 [-8.19387453e-02  7.51261017e-02 -3.26631810e-02  1.00000000e+00]]

Matrix Multiplication:
[[ 1

##●Use Probability concepts (basic probability, conditional probability, Bayes’ theorem, distributions)

In [18]:
from scipy.stats import norm, binom

url = "https://github.com/GeethaGunasekaran1/Dataset_rep/raw/refs/heads/main/Trip_Analysis.xlsx"

df = pd.read_excel(url)

print("\nDataset Loaded Successfully")

df = df.drop_duplicates().copy()

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:

    median_value = df[col].median()

    df[col] = df[col].fillna(median_value)

# Fill missing categorical values
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:

    if not df[col].mode().empty:

        mode_value = df[col].mode()[0]

        df[col] = df[col].fillna(mode_value)

print("\nData Cleaning Completed")

print("\n================ BASIC PROBABILITY ================")

total_rides = len(df)

print(f"\nTotal Number of Rides: {total_rides}")

# Choose first categorical column
if len(categorical_cols) > 0:

    category_col = categorical_cols[0]

    print(f"\nUsing Column: {category_col}")

    # Most frequent category
    most_common_category = df[category_col].mode()[0]

    favorable_cases = len(
        df[df[category_col] == most_common_category]
    )

    basic_probability = favorable_cases / total_rides

    print(f"\nMost Common Category: {most_common_category}")

    print(f"Probability of {most_common_category}:")
    print(basic_probability)

print("\n============ CONDITIONAL PROBABILITY =============")

if len(categorical_cols) >= 2:

    event_A_col = categorical_cols[0]

    event_B_col = categorical_cols[1]

    event_A = df[event_A_col].mode()[0]

    event_B = df[event_B_col].mode()[0]

    # P(A and B)
    intersection = len(
        df[
            (df[event_A_col] == event_A) &
            (df[event_B_col] == event_B)
        ]
    )

    # P(B)
    total_B = len(
        df[df[event_B_col] == event_B]
    )

    # Conditional Probability P(A|B)
    conditional_probability = intersection / total_B

    print(f"\nP({event_A} | {event_B}) =")
    print(conditional_probability)

print("\n================= BAYES THEOREM =================")

if len(categorical_cols) >= 2:

    # P(A)
    prob_A = len(
        df[df[event_A_col] == event_A]
    ) / total_rides

    # P(B)
    prob_B = len(
        df[df[event_B_col] == event_B]
    ) / total_rides

    # P(B|A)
    prob_B_given_A = intersection / len(
        df[df[event_A_col] == event_A]
    )

    # Bayes Theorem
    bayes_probability = (
        prob_B_given_A * prob_A
    ) / prob_B

    print(f"\nBayes Probability P({event_A}|{event_B}) =")
    print(bayes_probability)

print("\n=============== NORMAL DISTRIBUTION ===============")

if len(numeric_cols) > 0:

    numeric_col = numeric_cols[0]

    data = df[numeric_col]

    mean_value = np.mean(data)

    std_value = np.std(data)

    print(f"\nUsing Numeric Column: {numeric_col}")

    print(f"Mean: {mean_value}")

    print(f"Standard Deviation: {std_value}")

    # Probability for one value
    sample_value = mean_value

    normal_probability = norm.pdf(
        sample_value,
        mean_value,
        std_value
    )

    print(f"\nNormal Distribution Probability:")
    print(normal_probability)

print("\n============== BINOMIAL DISTRIBUTION ==============")

# Example assumptions
n = 10          # number of rides
p = 0.5         # success probability
x = 5           # successful rides

binomial_probability = binom.pmf(x, n, p)

print(f"\nBinomial Probability P(X={x}) =")
print(binomial_probability)


Dataset Loaded Successfully

Data Cleaning Completed

================ BASIC PROBABILITY ================

Total Number of Rides: 200

Using Column: Ride_Category

Most Common Category: Economy
Probability of Economy:
0.41

============ CONDITIONAL PROBABILITY =============

P(Economy | Peak) =
0.42718446601941745

================= BAYES THEOREM =================

Bayes Probability P(Economy|Peak) =
0.42718446601941745

=============== NORMAL DISTRIBUTION ===============

Using Numeric Column: Trip_Distance
Mean: 15.64
Standard Deviation: 8.41251448735751

Normal Distribution Probability:
0.04742247766716728

============== BINOMIAL DISTRIBUTION ==============

Binomial Probability P(X=5) =
0.24609375000000003


##●Perform Descriptive Statistics (mean, median, mode, variance, standard deviation, skewness, kurtosis)

In [19]:
import pandas as pd
import numpy as np

url = "https://github.com/GeethaGunasekaran1/Dataset_rep/raw/refs/heads/main/Trip_Analysis.xlsx"

df = pd.read_excel(url)

print("\nFirst 5 Rows of Dataset:")
print(df.head())

numeric_df = df.select_dtypes(include=[np.number])

descriptive_stats = pd.DataFrame({
    "Mean": numeric_df.mean(),
    "Median": numeric_df.median(),
    "Mode": numeric_df.mode().iloc[0],
    "Variance": numeric_df.var(),
    "Standard Deviation": numeric_df.std(),
    "Skewness": numeric_df.skew(),
    "Kurtosis": numeric_df.kurt()
})

descriptive_stats = descriptive_stats.round(4)

print("\nDescriptive Statistics:")
print(descriptive_stats)


First 5 Rows of Dataset:
   Trip_Distance  Fare_Amount Ride_Category  Surge_Multiplier  \
0              8   270.569350        Shared               2.5   
1             21   275.161032       Economy               2.5   
2             16   359.748971       Economy               2.0   
3             12   264.044264       Premium               1.5   
4              9   225.256916        Shared               2.0   

   Customer_Rating Ride_Time  
0                3  Non-Peak  
1                3  Non-Peak  
2                5  Non-Peak  
3                5  Non-Peak  
4                2  Non-Peak  

Descriptive Statistics:
                      Mean    Median     Mode   Variance  Standard Deviation  \
Trip_Distance      15.6400   15.0000  29.0000    71.1260              8.4336   
Fare_Amount       260.3124  256.9071  37.5859  6194.6545             78.7061   
Surge_Multiplier    1.6775    1.5000   1.0000     0.3013              0.5489   
Customer_Rating     2.9300    3.0000   1.0000     2.

##Detect outliers using percentiles, quartiles, IQR, and z-score

In [20]:
import pandas as pd
import numpy as np
from scipy.stats import zscore

url = "https://github.com/GeethaGunasekaran1/Dataset_rep/raw/refs/heads/main/Trip_Analysis.xlsx"

df = pd.read_excel(url)

numeric_df = df.select_dtypes(include=[np.number])

print("\nNumeric Columns:")
print(numeric_df.columns)

print("\n================ PERCENTILES ================\n")

for col in numeric_df.columns:
    p25 = np.percentile(numeric_df[col], 25)
    p50 = np.percentile(numeric_df[col], 50)
    p75 = np.percentile(numeric_df[col], 75)
    p95 = np.percentile(numeric_df[col], 95)

    print(f"\nColumn: {col}")
    print(f"25th Percentile : {p25:.2f}")
    print(f"50th Percentile : {p50:.2f}")
    print(f"75th Percentile : {p75:.2f}")
    print(f"95th Percentile : {p95:.2f}")

print("\n================ QUARTILES ================\n")

for col in numeric_df.columns:
    Q1 = numeric_df[col].quantile(0.25)
    Q2 = numeric_df[col].quantile(0.50)
    Q3 = numeric_df[col].quantile(0.75)

    print(f"\nColumn: {col}")
    print(f"Q1 : {Q1:.2f}")
    print(f"Q2 (Median) : {Q2:.2f}")
    print(f"Q3 : {Q3:.2f}")

print("\n================ IQR OUTLIERS ================\n")

iqr_outliers = {}

for col in numeric_df.columns:

    Q1 = numeric_df[col].quantile(0.25)
    Q3 = numeric_df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - (1.5 * IQR)
    upper_bound = Q3 + (1.5 * IQR)

    outliers = numeric_df[
        (numeric_df[col] < lower_bound) |
        (numeric_df[col] > upper_bound)
    ]

    iqr_outliers[col] = outliers

    print(f"\nColumn: {col}")
    print(f"IQR : {IQR:.2f}")
    print(f"Lower Bound : {lower_bound:.2f}")
    print(f"Upper Bound : {upper_bound:.2f}")
    print(f"Number of Outliers : {len(outliers)}")

print("\n================ Z-SCORE OUTLIERS ================\n")

zscore_outliers = {}

z_scores = np.abs(zscore(numeric_df))

for i, col in enumerate(numeric_df.columns):

    outliers = numeric_df[z_scores[:, i] > 3]

    zscore_outliers[col] = outliers

    print(f"\nColumn: {col}")
    print(f"Number of Outliers : {len(outliers)}")


Numeric Columns:
Index(['Trip_Distance', 'Fare_Amount', 'Surge_Multiplier', 'Customer_Rating'], dtype='object')

================ PERCENTILES ================


Column: Trip_Distance
25th Percentile : 8.00
50th Percentile : 15.00
75th Percentile : 23.00
95th Percentile : 29.00

Column: Fare_Amount
25th Percentile : 208.53
50th Percentile : 256.91
75th Percentile : 319.76
95th Percentile : 383.09

Column: Surge_Multiplier
25th Percentile : 1.00
50th Percentile : 1.50
75th Percentile : 2.00
95th Percentile : 2.50

Column: Customer_Rating
25th Percentile : 2.00
50th Percentile : 3.00
75th Percentile : 4.00
95th Percentile : 5.00

================ QUARTILES ================


Column: Trip_Distance
Q1 : 8.00
Q2 (Median) : 15.00
Q3 : 23.00

Column: Fare_Amount
Q1 : 208.53
Q2 (Median) : 256.91
Q3 : 319.76

Column: Surge_Multiplier
Q1 : 1.00
Q2 (Median) : 1.50
Q3 : 2.00

Column: Customer_Rating
Q1 : 2.00
Q2 (Median) : 3.00
Q3 : 4.00

================ IQR OUTLIERS ================


Column: Tr

#●Measure relationships using Pearson, Spearman, and covariance

In [21]:
# PEARSON CORRELATION

print("\n" + "=" * 60)
print("PEARSON CORRELATION MATRIX")
print("=" * 60)

pearson_corr = numeric_df.corr(method='pearson')

print(pearson_corr)

# SPEARMAN CORRELATION

print("\n" + "=" * 60)
print("SPEARMAN CORRELATION MATRIX")
print("=" * 60)

spearman_corr = numeric_df.corr(method='spearman')

print(spearman_corr)

# Measures Direction of Relationship

print("\n" + "=" * 60)
print("COVARIANCE MATRIX")
print("=" * 60)

covariance_matrix = numeric_df.cov()

print(covariance_matrix)

# INTERPRETATION OF CORRELATION

print("\n" + "=" * 60)
print("CORRELATION INTERPRETATION")
print("=" * 60)

for col1 in numeric_df.columns:
    for col2 in numeric_df.columns:

        if col1 != col2:

            corr_value = pearson_corr.loc[col1, col2]

            if abs(corr_value) > 0.7:
                relation = "Strong Relationship"
            elif abs(corr_value) > 0.4:
                relation = "Moderate Relationship"
            else:
                relation = "Weak Relationship"

            print(f"{col1} vs {col2} = {corr_value:.2f} --> {relation}")


PEARSON CORRELATION MATRIX
                  Trip_Distance  Fare_Amount  Surge_Multiplier  \
Trip_Distance          1.000000     0.016813          0.017131   
Fare_Amount            0.016813     1.000000          0.017419   
Surge_Multiplier       0.017131     0.017419          1.000000   
Customer_Rating       -0.084599     0.052723         -0.041304   

                  Customer_Rating  
Trip_Distance           -0.084599  
Fare_Amount              0.052723  
Surge_Multiplier        -0.041304  
Customer_Rating          1.000000  

SPEARMAN CORRELATION MATRIX
                  Trip_Distance  Fare_Amount  Surge_Multiplier  \
Trip_Distance          1.000000     0.023427          0.025459   
Fare_Amount            0.023427     1.000000          0.011764   
Surge_Multiplier       0.025459     0.011764          1.000000   
Customer_Rating       -0.082067     0.047499         -0.047091   

                  Customer_Rating  
Trip_Distance           -0.082067  
Fare_Amount              0.04

#Apply Inferential Statistics (bootstrapping, CLT, point & interval estimation)

In [22]:
target_column = numeric_cols[0]

data = df[target_column]

print("\nSelected Column for Inferential Statistics:")
print(target_column)

sample_size = len(data)
sample_mean = np.mean(data)
sample_std = np.std(data, ddof=1)

print("\n" + "=" * 60)
print("SAMPLE INFORMATION")
print("=" * 60)

print(f"Sample Size       : {sample_size}")
print(f"Sample Mean       : {sample_mean:.4f}")
print(f"Sample Std Dev    : {sample_std:.4f}")

print("\n" + "=" * 60)
print("CENTRAL LIMIT THEOREM (CLT)")
print("=" * 60)

# Generate sampling distribution
sample_means = []

num_samples = 1000
sample_n = 30

for i in range(num_samples):

    sample = np.random.choice(data, size=sample_n, replace=True)

    sample_means.append(np.mean(sample))

sample_means = np.array(sample_means)

clt_mean = np.mean(sample_means)
clt_std = np.std(sample_means)

print(f"Population Mean Approximation : {clt_mean:.4f}")
print(f"Sampling Distribution Std Dev : {clt_std:.4f}")

print("\nAccording to CLT:")
print("As sample size increases, sample means become normally distributed.")

print("\n" + "=" * 60)
print("POINT ESTIMATION")
print("=" * 60)

print(f"Point Estimate of Population Mean = {sample_mean:.4f}")

print("\n" + "=" * 60)
print("INTERVAL ESTIMATION (95% CONFIDENCE INTERVAL)")
print("=" * 60)

confidence_level = 0.95

# Standard Error
standard_error = sample_std / np.sqrt(sample_size)

# Z value for 95% confidence
z_value = stats.norm.ppf(0.975)

# Margin of Error
margin_error = z_value * standard_error

# Confidence Interval
lower_bound = sample_mean - margin_error
upper_bound = sample_mean + margin_error

print(f"Confidence Level : {confidence_level * 100}%")
print(f"Lower Bound      : {lower_bound:.4f}")
print(f"Upper Bound      : {upper_bound:.4f}")

print("\n" + "=" * 60)
print("BOOTSTRAPPING")
print("=" * 60)

bootstrap_means = []

bootstrap_iterations = 1000

for i in range(bootstrap_iterations):

    bootstrap_sample = np.random.choice(
        data,
        size=len(data),
        replace=True
    )

    bootstrap_means.append(np.mean(bootstrap_sample))

bootstrap_means = np.array(bootstrap_means)

bootstrap_mean = np.mean(bootstrap_means)

# Bootstrap Confidence Interval
bootstrap_ci_lower = np.percentile(bootstrap_means, 2.5)
bootstrap_ci_upper = np.percentile(bootstrap_means, 97.5)

print(f"Bootstrap Mean Estimate : {bootstrap_mean:.4f}")

print("\nBootstrap 95% Confidence Interval")
print(f"Lower Bound : {bootstrap_ci_lower:.4f}")
print(f"Upper Bound : {bootstrap_ci_upper:.4f}")

print("\n" + "=" * 60)
print("SUMMARY OF INFERENTIAL STATISTICS")
print("=" * 60)

print(f"""
1. Point Estimate:
   Estimated Population Mean = {sample_mean:.4f}

2. Interval Estimate:
   95% CI = ({lower_bound:.4f}, {upper_bound:.4f})

3. Bootstrapping:
   Bootstrap Mean = {bootstrap_mean:.4f}

4. Central Limit Theorem:
   Sampling distribution approximates normal distribution
   when sample size is sufficiently large.
""")


Selected Column for Inferential Statistics:
Trip_Distance

SAMPLE INFORMATION
Sample Size       : 200
Sample Mean       : 15.6400
Sample Std Dev    : 8.4336

CENTRAL LIMIT THEOREM (CLT)
Population Mean Approximation : 15.6224
Sampling Distribution Std Dev : 1.5545

According to CLT:
As sample size increases, sample means become normally distributed.

POINT ESTIMATION
Point Estimate of Population Mean = 15.6400

INTERVAL ESTIMATION (95% CONFIDENCE INTERVAL)
Confidence Level : 95.0%
Lower Bound      : 14.4712
Upper Bound      : 16.8088

BOOTSTRAPPING
Bootstrap Mean Estimate : 15.5998

Bootstrap 95% Confidence Interval
Lower Bound : 14.4850
Upper Bound : 16.7653

SUMMARY OF INFERENTIAL STATISTICS

1. Point Estimate:
   Estimated Population Mean = 15.6400

2. Interval Estimate:
   95% CI = (14.4712, 16.8088)

3. Bootstrapping:
   Bootstrap Mean = 15.5998

4. Central Limit Theorem:
   Sampling distribution approximates normal distribution
   when sample size is sufficiently large.



#●Conduct Hypothesis Testing (z-test, t-test, chi-square, F-test, ANOVA, A/B testing)

In [23]:
col1 = numeric_cols[0]
col2 = numeric_cols[1]

data1 = df[col1]
data2 = df[col2]

print("\nSelected Columns:")
print("Column 1:", col1)
print("Column 2:", col2)
alpha = 0.05

print("\n" + "=" * 70)
print("1. Z-TEST")
print("=" * 70)

mean1 = np.mean(data1)
mean2 = np.mean(data2)

std1 = np.std(data1, ddof=1)
std2 = np.std(data2, ddof=1)

n1 = len(data1)
n2 = len(data2)

# Z Statistic
z_stat = (mean1 - mean2) / np.sqrt((std1**2 / n1) + (std2**2 / n2))

# P-value
p_value_z = 2 * (1 - stats.norm.cdf(abs(z_stat)))

print(f"Z Statistic : {z_stat:.4f}")
print(f"P-value     : {p_value_z:.4f}")

if p_value_z < alpha:
    print("Result      : Reject Null Hypothesis")
else:
    print("Result      : Fail to Reject Null Hypothesis")


print("\n" + "=" * 70)
print("2. INDEPENDENT T-TEST")
print("=" * 70)

t_stat, p_value_t = stats.ttest_ind(data1, data2)

print(f"T Statistic : {t_stat:.4f}")
print(f"P-value     : {p_value_t:.4f}")

if p_value_t < alpha:
    print("Result      : Reject Null Hypothesis")
else:
    print("Result      : Fail to Reject Null Hypothesis")

print("\n" + "=" * 70)
print("3. CHI-SQUARE TEST")
print("=" * 70)

# Create categorical bins
cat1 = pd.cut(data1, bins=5)
cat2 = pd.cut(data2, bins=5)

# Contingency Table
contingency_table = pd.crosstab(cat1, cat2)

chi2_stat, p_value_chi, dof, expected = stats.chi2_contingency(contingency_table)

print(f"Chi-Square Statistic : {chi2_stat:.4f}")
print(f"P-value              : {p_value_chi:.4f}")
print(f"Degrees of Freedom   : {dof}")

if p_value_chi < alpha:
    print("Result               : Variables are dependent")
else:
    print("Result               : Variables are independent")

print("\n" + "=" * 70)
print("4. F-TEST")
print("=" * 70)

variance1 = np.var(data1, ddof=1)
variance2 = np.var(data2, ddof=1)

f_stat = variance1 / variance2

df1 = n1 - 1
df2 = n2 - 1

p_value_f = 1 - stats.f.cdf(f_stat, df1, df2)

print(f"F Statistic : {f_stat:.4f}")
print(f"P-value     : {p_value_f:.4f}")

if p_value_f < alpha:
    print("Result      : Variances are significantly different")
else:
    print("Result      : Variances are similar")

print("\n" + "=" * 70)
print("5. ANOVA TEST")
print("=" * 70)

# Create 3 sample groups from data1
group1 = data1.sample(frac=0.33, random_state=1)
group2 = data1.sample(frac=0.33, random_state=2)
group3 = data1.sample(frac=0.33, random_state=3)

anova_stat, p_value_anova = stats.f_oneway(group1, group2, group3)

print(f"ANOVA Statistic : {anova_stat:.4f}")
print(f"P-value         : {p_value_anova:.4f}")

if p_value_anova < alpha:
    print("Result          : At least one group mean differs")
else:
    print("Result          : Group means are similar")

print("\n" + "=" * 70)
print("6. A/B TESTING")
print("=" * 70)

# Simulated A/B Groups
A_group = data1.sample(frac=0.5, random_state=10)
B_group = data1.sample(frac=0.5, random_state=20)

ab_t_stat, ab_p_value = stats.ttest_ind(A_group, B_group)

print(f"A/B Test Statistic : {ab_t_stat:.4f}")
print(f"P-value            : {ab_p_value:.4f}")

if ab_p_value < alpha:
    print("Result             : Significant difference between A & B")
else:
    print("Result             : No significant difference between A & B")


Selected Columns:
Column 1: Trip_Distance
Column 2: Fare_Amount

1. Z-TEST
Z Statistic : -43.7132
P-value     : 0.0000
Result      : Reject Null Hypothesis

2. INDEPENDENT T-TEST
T Statistic : -43.7132
P-value     : 0.0000
Result      : Reject Null Hypothesis

3. CHI-SQUARE TEST
Chi-Square Statistic : 13.6763
P-value              : 0.6228
Degrees of Freedom   : 16
Result               : Variables are independent

4. F-TEST
F Statistic : 0.0115
P-value     : 1.0000
Result      : Variances are similar

5. ANOVA TEST
ANOVA Statistic : 1.6171
P-value         : 0.2011
Result          : Group means are similar

6. A/B TESTING
A/B Test Statistic : -0.8891
P-value            : 0.3750
Result             : No significant difference between A & B
